# Generated by Django 4.2.5 on 2023-09-27 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stduent',
            old_name='cgpa',
            new_name='gpa',
        ),
        migrations.RemoveField(
            model_name='stduent',
            name='address',
        ),
        migrations.AddField(
            model_name='stduent',
            name='is_graduated',
            field=models.BooleanField(default=False),
        ),
    ]
