# Generated by Django 4.2.5 on 2023-09-27 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_rename_cgpa_stduent_gpa_remove_stduent_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stduent',
            old_name='gpa',
            new_name='cgpa',
        ),
        migrations.RemoveField(
            model_name='stduent',
            name='is_graduated',
        ),
        migrations.AddField(
            model_name='stduent',
            name='address',
            field=models.TextField(default=''),
        ),
    ]
