# Generated by Django 4.2.5 on 2023-10-04 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_professor'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stduent',
            new_name='Student',
        ),
    ]
